package com.safaricom.api.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
@Table(name = "metadata_items")
public class MetadataItem {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "name")
    private String name;

    @Column(name = "value")
    private String value;

    @ManyToOne
    @JoinColumn(name = "callback_metadata_id")  // Foreign key column to CallbackMetadata
    private CallbackMetadata callbackMetadata;

    @ManyToOne
    @JoinColumn(name = "transaction_id")  // Foreign key column to MpesaTransaction
    private MpesaTransaction transaction;

    // Getter and Setter for 'callbackMetadata' and 'transaction' will be auto-generated by Lombok
}
